safe:
 - monty
 - pydash
 - networkx
 - maggma
 - pydantic
 - PyYAML
 - sphinx
 - furo
 - myst_parser
 - ipython
 - nbsphinx
 - autodoc_pydantic
 - pytest
 - pytest-cov
 - FireWorks
 - matplotlib
 - pydot
 - moto
 - pre-commit
