repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: fix-encoding-pragma
        args: [ --remove ]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args: [--in-place, --remove-all-unused-imports, --remove-unused-variable, --ignore-init-module-imports]
  - repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
    - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile=black]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        files: ^src/
        args:
        - --max-line-length=125
        - --extend-ignore=E203,W503,F401
        - --min-python-version=3.6.0
        language_version: python3
        additional_dependencies:
        - flake8-typing-imports==1.10.1
        - flake8-docstrings==1.5.0
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    - id: mypy
      files: ^src/
      args: [--no-strict-optional, --ignore-missing-imports]
      additional_dependencies:
        - iniconfig>=1.1.0
        - py>=1.8.2
        - packaging
        - tokenize-rt==3.2.0
