name: docs

on:
  workflow_run:
    workflows: [testing]
    branches: [main]
    types:
      - completed

jobs:

  docs:

    runs-on: ubuntu-latest

    # only run if commit is a push to master and the testing finished
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v2

      - name: Install pandoc
        run: sudo apt-get install pandoc

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[docs]
          pip install -e .[fireworks]

      - name: Build
        run: sphinx-build docs/src docs_build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs_build
