name: docs

on:
  push:
    branches:
      - main

jobs:

  docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          check-name: testing
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Install pandoc
        run: sudo apt-get install pandoc

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[docs]
          pip install -e .[fireworks]

      - name: Build
        run: sphinx-build docs/src docs_build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs_build
