name: release

on:
  push:
    tags:
      - 'v*'

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: main
          check-name: testing
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: wait on docs
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: main
          check-name: docs
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build packages
        run: |
          pip install setuptools setuptools_scm wheel
          python setup.py sdist bdist_wheel

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}

      - name: Write release info
        run: |
          awk 'BEGIN {p = 0} {a = 0 }; /^v\d*.\d*.\d*./ { p += 1; a = 1}; p + a == 1 { print } ' docs/src/changelog.rst | sed -e '1,1d' | sed  -e '/./,$!d' -e :a -e '/^\n*$/{$d;N;ba' -e '}' > release_info.txt

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: release_info.txt
          draft: false
          prerelease: false
