name: Run tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    services:
      local_mongodb:
        image: mongo:4.0
        ports:
          - 27017:27017

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-python@v2.2.2
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        pip install -r requirements.txt
        pip install .[tests]
        pip install .[fireworks]
        pip install .[vis]
        pip install .[S3]

    - name: Test
      run: pytest --cov=jobflow --cov-report=xml

    - uses: codecov/codecov-action@v1
      if: matrix.python-version == 3.8 && github.repository == 'hackingmaterials/jobflow'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
